### ISSUE TITLE
Icons aren't shown in the README

### ISSUE THREAD

**Issue by digitalcraftsman** [marloncabrera/tachyons#2]
The icons in the [icon reference table](https://github.com/marloncabrera/tachyons#icon-reference-table) of your README aren't shown.

**Comment by marloncabrera** [comment]
Thanks for the follow up. The icon reference table was fixed. The Geomicons author changed the repo path, also looks like Github didn't render SVG on markdow files anymore, I had to use http://rawgit.com to workaround.

/cc @jxnblk @digitalcraftsman
